School.WebApp/Models/DepartmentModel.cs
namespace School.WebApp.Models
{
    public class DepartmentModel
    {
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public decimal Budget { get; set; }
        public int Administrator { get; set; }
        public string StartDate { get; set; }
    }
}

School.WebApp/Models/ErrorViewModel.cs
namespace School.WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

School.WebApp/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using School.Application.Contract;
using School.Application.Dtos.Department;
using School.WebApp.Models;

namespace School.WebApp.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartamentService departamentService;

        public DepartmentController(IDepartamentService departamentService)
        {
            this.departamentService = departamentService;
        }

        // GET: DepartmentController
        public ActionResult Index()
        {
            var result = this.departamentService.Get();

            if (!result.Success)
            {
                ViewBag.Message = result.Message;
                return View();
            }

            var deparments = ((List<Infrastructure.Models.DepartmentModel>)result.Data)
                                                  .Select(cd => new Models.DepartmentModel()
                                                  {

                                                      Administrator = cd.Administrator.Value, 
                                                      DepartmentId = cd.DepartmentId, 
                                                      Name= cd.Name,
                                                      Budget = cd.Budget, 
                                                      StartDate = cd.StartDate.ToString("dd/MM/yyyy")
                                                  }).ToList();

            return View(deparments);
        }

        // GET: DepartmentController/Details/5
        public ActionResult Details(int id)
        {
            var result = this.departamentService.GetById(id);

            if (!result.Success)
            {
                ViewBag.Message = result.Message;
                return View();
            }

            var depto = (Infrastructure.Models.DepartmentModel)result.Data;

            var deptModel = new Models.DepartmentModel()
            {

                Administrator = depto.Administrator.Value,
                DepartmentId = depto.DepartmentId,
                Name = depto.Name,
                Budget = depto.Budget,
                StartDate = depto.StartDate.ToString("dd/MM/yyyy")
            };

            return View(deptModel);
            
        }

        // GET: DepartmentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DepartmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DepartmentAddDto departmentAddDto)
        {
            try
            {
                var result = this.departamentService.Save(departmentAddDto);

                if (!result.Success)
                {
                    ViewBag.Message = result.Message;
                    return View();
                }



                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DepartmentController/Edit/5
        public ActionResult Edit(int id)
        {


            var result = this.departamentService.GetById(id);

            if (!result.Success)
            {
                ViewBag.Message = result.Message;
                return View();
            }

            var depto = (Infrastructure.Models.DepartmentModel)result.Data;

            var deptModel = new Models.DepartmentModel()
            {

                Administrator = depto.Administrator.Value,
                DepartmentId = depto.DepartmentId,
                Name = depto.Name,
                Budget = depto.Budget,
                StartDate = depto.StartDate.ToString("dd/MM/yyyy")
            };

            return View(deptModel);
        }

        // POST: DepartmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DepartmentUpdateDto departmentUpdate)
        {
            try
            {
                var result = this.departamentService.Update(departmentUpdate);

                if (!result.Success)
                {
                    ViewBag.Message = result.Message;
                    return View();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


    }
}

School.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using School.WebApp.Models;
using System.Diagnostics;

namespace School.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

School.WebApp/Views/Department/Create.cshtml
@model School.WebApp.Models.DepartmentModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Department</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Administrator" class="control-label"></label>
                <input asp-for="Administrator" class="form-control" />
                <span asp-validation-for="Administrator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <input type="reset" value="Clear" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School.WebApp/Views/Department/Details.cshtml
@model School.WebApp.Models.DepartmentModel

@{
    ViewData["Title"] = "Details";
}

<h1>Department Details</h1>

<div>
   
    <hr />
    <dl class="row">
       
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Budget)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Administrator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Administrator)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DepartmentId  }) |
    <a asp-action="Index">Back to List</a>
</div>

School.WebApp/Views/Department/Edit.cshtml
@model School.WebApp.Models.DepartmentModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Department</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <input asp-for="DepartmentId" class="form-control" readonly />
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Administrator" class="control-label"></label>
                <input asp-for="Administrator" class="form-control" />
                <span asp-validation-for="Administrator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <input type="reset" value="Clear" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School.WebApp/Views/Department/Index.cshtml
@model IEnumerable<School.WebApp.Models.DepartmentModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Departments</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Budget)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Administrator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Budget)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Administrator)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id= item.DepartmentId }) |
                @Html.ActionLink("Details", "Details", new {  id=item.DepartmentId }) 
               
            </td>
        </tr>
}
    </tbody>
</table>

School.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

School.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/School.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - School.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>